=== Toxa1987/XmlTask/src/main/resources/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gems">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="gem" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Id" type="customId" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="customId">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-zA-z]{5}\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="visualParametersType">
        <xs:sequence>
            <xs:element name="color" default="Colorless">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="transparency" default="100">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:maxInclusive value="100"/>
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gemType">
        <xs:sequence>
            <xs:element name="name">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][a-z]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="origin">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Russia"/>
                        <xs:enumeration value="Columbia"/>
                        <xs:enumeration value="Myanmar"/>
                        <xs:enumeration value="USA"/>
                        <xs:enumeration value="Brazil"/>
                        <xs:enumeration value="Czech"/>
                        <xs:enumeration value="Madagascar"/>
                        <xs:enumeration value="Tanzania"/>
                        <xs:enumeration value="South Africa"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="hardness">
                <xs:simpleType>
                    <xs:restriction base="xs:byte">
                        <xs:enumeration value="10"/>
                        <xs:enumeration value="8"/>
                        <xs:enumeration value="9"/>
                        <xs:enumeration value="7"/>
                        <xs:enumeration value="6"/>
                        <xs:enumeration value="5"/>
                        <xs:enumeration value="4"/>
                        <xs:enumeration value="3"/>
                        <xs:enumeration value="2"/>
                        <xs:enumeration value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="value">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="timeOfExtraction" type="xs:gYearMonth"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="preciousType">
        <xs:complexContent>
            <xs:extension base="gemType">
                <xs:sequence>
                    <xs:element type="visualParametersType" name="visualParameters"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="semipreciousType">
        <xs:complexContent>
            <xs:extension base="gemType">
                <xs:sequence>
                    <xs:element type="visualParametersType" name="visualParameters"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="gem" type="gemType" abstract="true"/>
    <xs:element name="Precious" type="preciousType" substitutionGroup="gem"/>
    <xs:element name="Semiprecious" type="semipreciousType" substitutionGroup="gem"/>

</xs:schema>

=== Toxa1987/XmlTask/src/main/resources/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gems.xsd" Id="Anton123">

    <Precious>
        <name>Diamond</name>
        <origin>Russia</origin>
        <hardness>10</hardness>
        <value >5</value>
        <timeOfExtraction>2020-03</timeOfExtraction>
        <visualParameters>
            <color>Colorless</color>
            <transparency>100</transparency>
        </visualParameters>
    </Precious>
    <Precious>
        <name>Emerald</name>
        <origin>Columbia</origin>
        <hardness>8</hardness>
        <value>4</value>
        <timeOfExtraction>2020-04</timeOfExtraction>
        <visualParameters>
            <color>Green</color>
            <transparency>98</transparency>
        </visualParameters>
    </Precious>
    <Precious>
        <name>Ruby</name>
        <origin>Myanmar</origin>
        <hardness>9</hardness>
        <value>10</value>
        <timeOfExtraction>2020-05</timeOfExtraction>
        <visualParameters>
            <color>Red</color>
            <transparency>99</transparency>
        </visualParameters>
    </Precious>
    <Precious>
        <name>Sapphire</name>
        <origin>USA</origin>
        <hardness>9</hardness>
        <value>5</value>
        <timeOfExtraction>2020-01</timeOfExtraction>
        <visualParameters>
            <color>Blue</color>
            <transparency>95</transparency>
        </visualParameters>
    </Precious>
    <Semiprecious>
        <name>Aquamarine</name>
        <origin>Russia</origin>
        <hardness>8</hardness>
        <value>5</value>
        <timeOfExtraction>2021-03</timeOfExtraction>
        <visualParameters>
            <color>Blue</color>
            <transparency>99</transparency>
        </visualParameters>
    </Semiprecious>
    <Precious>
        <name>Beryl</name>
        <origin>Brazil</origin>
        <hardness>8</hardness>
        <value>50</value>
        <timeOfExtraction>2021-01</timeOfExtraction>
        <visualParameters>
            <color>Colorless</color>
            <transparency>99</transparency>
        </visualParameters>
    </Precious>
    <Precious>
        <name>Alexandrite</name>
        <origin>Russia</origin>
        <hardness>8</hardness>
        <value>1</value>
        <timeOfExtraction>2020-06</timeOfExtraction>
        <visualParameters>
            <color>Purple</color>
            <transparency>98</transparency>
        </visualParameters>
    </Precious>
    <Semiprecious>
        <name>Pirop</name>
        <origin>Czech</origin>
        <hardness>7</hardness>
        <value>10</value>
        <timeOfExtraction>2020-09</timeOfExtraction>
        <visualParameters>
            <color>Red</color>
            <transparency>80</transparency>
        </visualParameters>
    </Semiprecious>
    <Semiprecious>
        <name>Amethyst</name>
        <origin>Brazil</origin>
        <hardness>7</hardness>
        <value>6</value>
        <timeOfExtraction>2021-02</timeOfExtraction>
        <visualParameters>
            <color>Purple</color>
            <transparency>90</transparency>
        </visualParameters>
    </Semiprecious>
    <Semiprecious>
        <name>Tourmaline</name>
        <origin>Madagascar</origin>
        <hardness>7</hardness>
        <value>8</value>
        <timeOfExtraction>2020-10</timeOfExtraction>
        <visualParameters>
            <color>Red</color>
            <transparency>85</transparency>
        </visualParameters>
    </Semiprecious>
    <Semiprecious>
        <name>Topaz</name>
        <origin>Russia</origin>
        <hardness>7</hardness>
        <value>10</value>
        <timeOfExtraction>2020-12</timeOfExtraction>
        <visualParameters>
            <color>Viol</color>
            <transparency>80</transparency>
        </visualParameters>
    </Semiprecious>
    <Semiprecious>
        <name>Tanzanite</name>
        <origin>Tanzania</origin>
        <hardness>6</hardness>
        <value>11</value>
        <timeOfExtraction>2020-07</timeOfExtraction>
        <visualParameters>
            <color>Blue</color>
            <transparency>95</transparency>
        </visualParameters>
    </Semiprecious>
    <Precious>
        <name>Emerald</name>
        <origin>Columbia</origin>
        <hardness>8</hardness>
        <value>20</value>
        <timeOfExtraction>2020-06</timeOfExtraction>
        <visualParameters>
            <color>Green</color>
            <transparency>90</transparency>
        </visualParameters>
    </Precious>
    <Precious>
        <name>Ruby</name>
        <origin>Myanmar</origin>
        <hardness>9</hardness>
        <value>5</value>
        <timeOfExtraction>2020-02</timeOfExtraction>
        <visualParameters>
            <color>Red</color>
            <transparency>96</transparency>
        </visualParameters>
    </Precious>
    <Semiprecious>
        <name>Amethyst</name>
        <origin>Brazil</origin>
        <hardness>7</hardness>
        <value>15</value>
        <timeOfExtraction>2020-02</timeOfExtraction>
        <visualParameters>
            <color>Purple</color>
            <transparency>97</transparency>
        </visualParameters>
    </Semiprecious>
    <Semiprecious>
        <name>Tourmaline</name>
        <origin>South Africa</origin>
        <hardness>7</hardness>
        <value>30</value>
        <timeOfExtraction>2020-01</timeOfExtraction>
        <visualParameters>
            <color>Green</color>
            <transparency>90</transparency>
        </visualParameters>
    </Semiprecious>
</gems>
